http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
pipeline.workers: 1
queue.type: persisted
queue.max_bytes: 1073741824
queue.checkpoint.interval: 1000
queue.page_capacity: 8388608